import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount, useChainId } from "wagmi";
import Dashboard from "../component/dashboard/Dashboard";

const Home: NextPage = () => {
  const { address } = useAccount();
  const chainID = useChainId();

  if (!address) {
    return (
      <div>
        <div className={styles.mainH}>
          <h1 className={styles.title}>
            Welcome to <a href="">RebasedAI</a>
          </h1>
          <ConnectButton />
          <h1 className={styles.title}>to View Dashboard</h1>
        </div>
      </div>
    );
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>
        <Dashboard />
        {chainID}
        <footer className={styles.footer}>
          <a
            href="https://rainbow.me"
            rel="noopener noreferrer"
            target="_blank"
          >
            Made with ❤️ by your frens at 🌈
          </a>
        </footer>
      </div>
    );
  }
};

export default Home;
